spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
springdoc:
  api-docs:
    path: /api-docs
