spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tinyurl?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: robert
    password: robert159

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
